//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FF_NSBB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRAFT
    {
        public int ID { get; set; }
        public int TEAMID { get; set; }
        public Nullable<int> DRAFT1 { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
