//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FF_NSBB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FF_League
    {
        public int ID { get; set; }
        public Nullable<int> TEAMID { get; set; }
        public Nullable<int> PLAYERID { get; set; }
    
        public virtual FF_Player FF_Player { get; set; }
    }
}
