//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FF_NSBB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FF_Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FF_Player()
        {
            this.FF_League = new HashSet<FF_League>();
        }
    
        public int ID { get; set; }
        public string FIRST { get; set; }
        public string LAST { get; set; }
        public Nullable<double> ADP { get; set; }
        public string TEAM { get; set; }
        public Nullable<int> BYE { get; set; }
        public string POS { get; set; }
        public Nullable<int> VBD { get; set; }
        public Nullable<int> PTS { get; set; }
        public Nullable<int> OVERALL { get; set; }
        public Nullable<bool> DRAFTED { get; set; }
        public Nullable<bool> MYTEAM { get; set; }
        public string SID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FF_League> FF_League { get; set; }
    }
}
