//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FF_NSBB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FF_Team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FF_Team()
        {
            this.FF_DRAFT = new HashSet<FF_DRAFT>();
        }
    
        public int ID { get; set; }
        public string TeamName { get; set; }
        public string TeamManager { get; set; }
        public string Picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FF_DRAFT> FF_DRAFT { get; set; }
    }
}
