//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FF_NSBB.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FF2014Entities : DbContext
    {
        public FF2014Entities()
            : base("name=FF2014Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FF_DRAFT> FF_DRAFT { get; set; }
        public virtual DbSet<FF_League> FF_League { get; set; }
        public virtual DbSet<FF_Player> FF_Player { get; set; }
        public virtual DbSet<FF_TAKEN> FF_TAKEN { get; set; }
        public virtual DbSet<FF_Team> FF_Team { get; set; }
        public virtual DbSet<FF_Turn> FF_Turn { get; set; }
    }
}
